package com.spartan.dms.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Request DTO used for BOTH create (POST) and update (PUT).
 *
 * IMPORTANT (root cause of the "Row was updated or deleted by another
 * transaction" error):
 * This DTO must NEVER contain an "id" field. The primary key is only ever
 * known from:
 *   - create -> generated by the database (IDENTITY strategy), never supplied
 *   - update -> taken from the URL path variable /{id}, never from the body
 *
 * If an "id" ever gets added here and the frontend echoes back a previously
 * loaded product's id while creating a new one, ModelMapper will copy that
 * id onto a brand-new (transient) Product entity. Spring Data JPA's
 * save() then sees a non-null id, assumes the entity already exists, and
 * calls entityManager.merge() (UPDATE) instead of persist() (INSERT).
 * Since no row with that id was actually being edited, 0 rows are updated
 * and Hibernate throws exactly the StaleObjectStateException seen in the
 * screenshot. Keep this DTO id-free to make that failure mode impossible.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductRequest {

    @NotBlank(message = "Product name is required")
    private String productName;

    @NotBlank(message = "Product code is required")
    private String productCode;

    private String barcode;

    private String hsnSacCode;

    private String batchNumber;

    @NotNull(message = "Category is required")
    private Long categoryId;

    private String brandName;

    private String unit;

    @NotNull(message = "Stock quantity is required")
    @DecimalMin(value = "0", message = "Stock quantity cannot be negative")
    private Integer stockQuantity;

    @jakarta.validation.constraints.DecimalMin(value = "0", message = "Minimum stock cannot be negative")
    private Integer minimumStock;

    @NotNull(message = "Purchase price is required")
    @DecimalMin(value = "0", inclusive = true, message = "Purchase price cannot be negative")
    private BigDecimal purchasePrice;

    // Tier 1: Company -> Super Stockist rate. Admin-only, set on the
    // product master. Optional so existing products / simpler setups
    // aren't forced to fill it in immediately.
    @DecimalMin(value = "0", inclusive = true, message = "SS price cannot be negative")
    private BigDecimal ssPrice;

    // Tier 2: Super Stockist -> Distributor rate ("DP").
    @DecimalMin(value = "0", inclusive = true, message = "Distributor price cannot be negative")
    private BigDecimal distributorPrice;

    @NotNull(message = "Selling price is required")
    @DecimalMin(value = "0", inclusive = true, message = "Selling price cannot be negative")
    private BigDecimal sellingPrice;

    @DecimalMin(value = "0", inclusive = true, message = "MRP cannot be negative")
    private BigDecimal mrp;

    @jakarta.validation.constraints.DecimalMin(value = "0", inclusive = true, message = "GST % cannot be negative")
    @jakarta.validation.constraints.DecimalMax(value = "100", inclusive = true, message = "GST % cannot exceed 100")
    private BigDecimal gstPercentage;

    private String description;

    private Boolean active;
}